### ISSUE TITLE
Real front and rear axles

### ISSUE THREAD

**Issue by rogeriodec** [rasmaxim/pygame-car-tutorial#1]
Thank a lot for your http://rmgi.blog/pygame-2d-car-tutorial.htm tutorial.
I have a doubt about the steering. 
As specified by Ackermann steering geometry - and I think you did right - the steering is based mainly in a central imaginary front tire. 
What I didn't get to understand is where exactly this central tire is positioned. 
I say this because, in a real car, the front and rear axles are not at the ends of the final rectangle of the car, ie the front axle is tens of centimeters behind the front bumper and so does the rear axle.
How to make the correct calculation in a car 4 meters in length, and the front axle would be, for example, usually 70 cm before the front end and the same with the rear axle?

**Comment by maximryzhov** [comment]
Hello, rogeriodec. Unfortunately, I am not an expert and can't give you a competent answer. This hobby project is just an attempt to make an interactive 2D car animation, and by no means is a simulation of a real vehicle. For some real numbers you may try to look for papers on this topic, like http://entertain.univie.ac.at/~hlavacs/publications/car_model06.pdf

As far as my approach goes, I beleive there's no "correct calculation" for arcade games, because the main point is to make the game mechanics feel right, not to actually be physically correct.

**Comment by rogeriodec** [comment]
> [http://entertain.univie.ac.at/~hlavacs/publications/car_model06.pdf](http://entertain.univie.ac.at/%7Ehlavacs/publications/car_model06.pdf)
> 

This is really a good document, thank you again!
